twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        cdn_veaf: '%cdn_veaf%'
    form_themes:
      - 'bootstrap_4_layout.html.twig'
      - '@TetranzSelect2Entity/Form/fields.html.twig'
