twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        cdn_url: '%cdn_url%'
        google_agent: '%google_agent%'
        app_version: '%app_version%'
        website: '%website%'
        registration_disabled: '%registration_disabled%'
    form_themes:
      - 'bootstrap_4_layout.html.twig'
      - '@TetranzSelect2Entity/Form/fields.html.twig'
