controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

# to force CMS controller at the end
cms:
    resource: ../../src/Controller/PageController.php
    type: annotation
