<?php
/**
 * ServerStatsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DcsServerBot\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServerStatsTest Class Doc Comment
 *
 * @category    Class
 * @description ServerStats
 * @package     DcsServerBot
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServerStatsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServerStats"
     */
    public function testServerStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_players"
     */
    public function testPropertyTotalPlayers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_playtime"
     */
    public function testPropertyAvgPlaytime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_playtime"
     */
    public function testPropertyTotalPlaytime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "active_players"
     */
    public function testPropertyActivePlayers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_sorties"
     */
    public function testPropertyTotalSorties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_kills"
     */
    public function testPropertyTotalKills()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_deaths"
     */
    public function testPropertyTotalDeaths()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_pv_p_kills"
     */
    public function testPropertyTotalPvPKills()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_pv_p_deaths"
     */
    public function testPropertyTotalPvPDeaths()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "daily_players"
     */
    public function testPropertyDailyPlayers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
