<?php
/**
 * TopMissionTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DcsServerBot\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TopMissionTest Class Doc Comment
 *
 * @category    Class
 * @description TopMission
 * @package     DcsServerBot
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TopMissionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TopMission"
     */
    public function testTopMission()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mission_name"
     */
    public function testPropertyMissionName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "playtime_hours"
     */
    public function testPropertyPlaytimeHours()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
