<?php
/**
 * CreditsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use DcsServerBot\ApiException;
use DcsServerBot\Configuration;
use DcsServerBot\FormDataProcessor;
use DcsServerBot\HeaderSelector;
use DcsServerBot\ObjectSerializer;

/**
 * CreditsApi Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CreditsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'creditsServerapiCreditsPost' => [
            'application/x-www-form-urlencoded',
        ],
        'squadronCreditsServerapiSquadronCreditsPost' => [
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation creditsServerapiCreditsPost
     *
     * Campaign Credits
     *
     * @param  string $nick nick (required)
     * @param  string|null $date date (optional)
     * @param  string|null $campaign campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['creditsServerapiCreditsPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\CampaignCredits|\DcsServerBot\Model\HTTPValidationError
     */
    public function creditsServerapiCreditsPost($nick, $date = null, $campaign = null, string $contentType = self::contentTypes['creditsServerapiCreditsPost'][0])
    {
        list($response) = $this->creditsServerapiCreditsPostWithHttpInfo($nick, $date, $campaign, $contentType);
        return $response;
    }

    /**
     * Operation creditsServerapiCreditsPostWithHttpInfo
     *
     * Campaign Credits
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['creditsServerapiCreditsPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\CampaignCredits|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function creditsServerapiCreditsPostWithHttpInfo($nick, $date = null, $campaign = null, string $contentType = self::contentTypes['creditsServerapiCreditsPost'][0])
    {
        $request = $this->creditsServerapiCreditsPostRequest($nick, $date, $campaign, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\CampaignCredits',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\CampaignCredits',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\CampaignCredits',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation creditsServerapiCreditsPostAsync
     *
     * Campaign Credits
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['creditsServerapiCreditsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function creditsServerapiCreditsPostAsync($nick, $date = null, $campaign = null, string $contentType = self::contentTypes['creditsServerapiCreditsPost'][0])
    {
        return $this->creditsServerapiCreditsPostAsyncWithHttpInfo($nick, $date, $campaign, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation creditsServerapiCreditsPostAsyncWithHttpInfo
     *
     * Campaign Credits
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['creditsServerapiCreditsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function creditsServerapiCreditsPostAsyncWithHttpInfo($nick, $date = null, $campaign = null, string $contentType = self::contentTypes['creditsServerapiCreditsPost'][0])
    {
        $returnType = '\DcsServerBot\Model\CampaignCredits';
        $request = $this->creditsServerapiCreditsPostRequest($nick, $date, $campaign, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'creditsServerapiCreditsPost'
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['creditsServerapiCreditsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function creditsServerapiCreditsPostRequest($nick, $date = null, $campaign = null, string $contentType = self::contentTypes['creditsServerapiCreditsPost'][0])
    {

        // verify the required parameter 'nick' is set
        if ($nick === null || (is_array($nick) && count($nick) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nick when calling creditsServerapiCreditsPost'
            );
        }




        $resourcePath = '/serverapi/credits';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'nick' => $nick,
            'date' => $date,
            'campaign' => $campaign,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation squadronCreditsServerapiSquadronCreditsPost
     *
     * Squadron Credits
     *
     * @param  string $name name (required)
     * @param  string|null $campaign campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\SquadronCampaignCredit|\DcsServerBot\Model\HTTPValidationError
     */
    public function squadronCreditsServerapiSquadronCreditsPost($name, $campaign = null, string $contentType = self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'][0])
    {
        list($response) = $this->squadronCreditsServerapiSquadronCreditsPostWithHttpInfo($name, $campaign, $contentType);
        return $response;
    }

    /**
     * Operation squadronCreditsServerapiSquadronCreditsPostWithHttpInfo
     *
     * Squadron Credits
     *
     * @param  string $name (required)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\SquadronCampaignCredit|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function squadronCreditsServerapiSquadronCreditsPostWithHttpInfo($name, $campaign = null, string $contentType = self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'][0])
    {
        $request = $this->squadronCreditsServerapiSquadronCreditsPostRequest($name, $campaign, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\SquadronCampaignCredit',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\SquadronCampaignCredit',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\SquadronCampaignCredit',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation squadronCreditsServerapiSquadronCreditsPostAsync
     *
     * Squadron Credits
     *
     * @param  string $name (required)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function squadronCreditsServerapiSquadronCreditsPostAsync($name, $campaign = null, string $contentType = self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'][0])
    {
        return $this->squadronCreditsServerapiSquadronCreditsPostAsyncWithHttpInfo($name, $campaign, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation squadronCreditsServerapiSquadronCreditsPostAsyncWithHttpInfo
     *
     * Squadron Credits
     *
     * @param  string $name (required)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function squadronCreditsServerapiSquadronCreditsPostAsyncWithHttpInfo($name, $campaign = null, string $contentType = self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'][0])
    {
        $returnType = '\DcsServerBot\Model\SquadronCampaignCredit';
        $request = $this->squadronCreditsServerapiSquadronCreditsPostRequest($name, $campaign, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'squadronCreditsServerapiSquadronCreditsPost'
     *
     * @param  string $name (required)
     * @param  string|null $campaign (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function squadronCreditsServerapiSquadronCreditsPostRequest($name, $campaign = null, string $contentType = self::contentTypes['squadronCreditsServerapiSquadronCreditsPost'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling squadronCreditsServerapiSquadronCreditsPost'
            );
        }



        $resourcePath = '/serverapi/squadron_credits';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'name' => $name,
            'campaign' => $campaign,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
