<?php
/**
 * InfoApi
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use DcsServerBot\ApiException;
use DcsServerBot\Configuration;
use DcsServerBot\FormDataProcessor;
use DcsServerBot\HeaderSelector;
use DcsServerBot\ObjectSerializer;

/**
 * InfoApi Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InfoApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'currentServerServerapiCurrentServerGet' => [
            'application/json',
        ],
        'getuserServerapiGetuserPost' => [
            'application/x-www-form-urlencoded',
        ],
        'linkmeServerapiLinkmePost' => [
            'application/x-www-form-urlencoded',
        ],
        'playerSquadronsServerapiPlayerSquadronsPost' => [
            'application/x-www-form-urlencoded',
        ],
        'serversServerapiServersGet' => [
            'application/json',
        ],
        'serverstatsServerapiServerstatsGet' => [
            'application/json',
        ],
        'squadronMembersServerapiSquadronMembersPost' => [
            'application/x-www-form-urlencoded',
        ],
        'squadronsServerapiSquadronsGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation currentServerServerapiCurrentServerGet
     *
     * Current Server
     *
     * @param  string $nick nick (required)
     * @param  string|null $date date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['currentServerServerapiCurrentServerGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string|\DcsServerBot\Model\HTTPValidationError
     */
    public function currentServerServerapiCurrentServerGet($nick, $date = null, string $contentType = self::contentTypes['currentServerServerapiCurrentServerGet'][0])
    {
        list($response) = $this->currentServerServerapiCurrentServerGetWithHttpInfo($nick, $date, $contentType);
        return $response;
    }

    /**
     * Operation currentServerServerapiCurrentServerGetWithHttpInfo
     *
     * Current Server
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['currentServerServerapiCurrentServerGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function currentServerServerapiCurrentServerGetWithHttpInfo($nick, $date = null, string $contentType = self::contentTypes['currentServerServerapiCurrentServerGet'][0])
    {
        $request = $this->currentServerServerapiCurrentServerGetRequest($nick, $date, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation currentServerServerapiCurrentServerGetAsync
     *
     * Current Server
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['currentServerServerapiCurrentServerGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function currentServerServerapiCurrentServerGetAsync($nick, $date = null, string $contentType = self::contentTypes['currentServerServerapiCurrentServerGet'][0])
    {
        return $this->currentServerServerapiCurrentServerGetAsyncWithHttpInfo($nick, $date, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation currentServerServerapiCurrentServerGetAsyncWithHttpInfo
     *
     * Current Server
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['currentServerServerapiCurrentServerGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function currentServerServerapiCurrentServerGetAsyncWithHttpInfo($nick, $date = null, string $contentType = self::contentTypes['currentServerServerapiCurrentServerGet'][0])
    {
        $returnType = 'string';
        $request = $this->currentServerServerapiCurrentServerGetRequest($nick, $date, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'currentServerServerapiCurrentServerGet'
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['currentServerServerapiCurrentServerGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function currentServerServerapiCurrentServerGetRequest($nick, $date = null, string $contentType = self::contentTypes['currentServerServerapiCurrentServerGet'][0])
    {

        // verify the required parameter 'nick' is set
        if ($nick === null || (is_array($nick) && count($nick) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nick when calling currentServerServerapiCurrentServerGet'
            );
        }



        $resourcePath = '/serverapi/current_server';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nick,
            'nick', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date,
            'date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getuserServerapiGetuserPost
     *
     * User list
     *
     * @param  string $nick nick (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getuserServerapiGetuserPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\UserEntry[]|\DcsServerBot\Model\HTTPValidationError
     */
    public function getuserServerapiGetuserPost($nick, string $contentType = self::contentTypes['getuserServerapiGetuserPost'][0])
    {
        list($response) = $this->getuserServerapiGetuserPostWithHttpInfo($nick, $contentType);
        return $response;
    }

    /**
     * Operation getuserServerapiGetuserPostWithHttpInfo
     *
     * User list
     *
     * @param  string $nick (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getuserServerapiGetuserPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\UserEntry[]|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getuserServerapiGetuserPostWithHttpInfo($nick, string $contentType = self::contentTypes['getuserServerapiGetuserPost'][0])
    {
        $request = $this->getuserServerapiGetuserPostRequest($nick, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\UserEntry[]',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\UserEntry[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\UserEntry[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getuserServerapiGetuserPostAsync
     *
     * User list
     *
     * @param  string $nick (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getuserServerapiGetuserPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getuserServerapiGetuserPostAsync($nick, string $contentType = self::contentTypes['getuserServerapiGetuserPost'][0])
    {
        return $this->getuserServerapiGetuserPostAsyncWithHttpInfo($nick, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getuserServerapiGetuserPostAsyncWithHttpInfo
     *
     * User list
     *
     * @param  string $nick (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getuserServerapiGetuserPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getuserServerapiGetuserPostAsyncWithHttpInfo($nick, string $contentType = self::contentTypes['getuserServerapiGetuserPost'][0])
    {
        $returnType = '\DcsServerBot\Model\UserEntry[]';
        $request = $this->getuserServerapiGetuserPostRequest($nick, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getuserServerapiGetuserPost'
     *
     * @param  string $nick (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getuserServerapiGetuserPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getuserServerapiGetuserPostRequest($nick, string $contentType = self::contentTypes['getuserServerapiGetuserPost'][0])
    {

        // verify the required parameter 'nick' is set
        if ($nick === null || (is_array($nick) && count($nick) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nick when calling getuserServerapiGetuserPost'
            );
        }


        $resourcePath = '/serverapi/getuser';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'nick' => $nick,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation linkmeServerapiLinkmePost
     *
     * Link Discord to DCS
     *
     * @param  string $discord_id Discord user ID (snowflake) (required)
     * @param  bool|null $force Force the operation (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkmeServerapiLinkmePost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\LinkMeResponse|\DcsServerBot\Model\HTTPValidationError
     */
    public function linkmeServerapiLinkmePost($discord_id, $force = false, string $contentType = self::contentTypes['linkmeServerapiLinkmePost'][0])
    {
        list($response) = $this->linkmeServerapiLinkmePostWithHttpInfo($discord_id, $force, $contentType);
        return $response;
    }

    /**
     * Operation linkmeServerapiLinkmePostWithHttpInfo
     *
     * Link Discord to DCS
     *
     * @param  string $discord_id Discord user ID (snowflake) (required)
     * @param  bool|null $force Force the operation (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkmeServerapiLinkmePost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\LinkMeResponse|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function linkmeServerapiLinkmePostWithHttpInfo($discord_id, $force = false, string $contentType = self::contentTypes['linkmeServerapiLinkmePost'][0])
    {
        $request = $this->linkmeServerapiLinkmePostRequest($discord_id, $force, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\LinkMeResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\LinkMeResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\LinkMeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation linkmeServerapiLinkmePostAsync
     *
     * Link Discord to DCS
     *
     * @param  string $discord_id Discord user ID (snowflake) (required)
     * @param  bool|null $force Force the operation (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkmeServerapiLinkmePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function linkmeServerapiLinkmePostAsync($discord_id, $force = false, string $contentType = self::contentTypes['linkmeServerapiLinkmePost'][0])
    {
        return $this->linkmeServerapiLinkmePostAsyncWithHttpInfo($discord_id, $force, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation linkmeServerapiLinkmePostAsyncWithHttpInfo
     *
     * Link Discord to DCS
     *
     * @param  string $discord_id Discord user ID (snowflake) (required)
     * @param  bool|null $force Force the operation (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkmeServerapiLinkmePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function linkmeServerapiLinkmePostAsyncWithHttpInfo($discord_id, $force = false, string $contentType = self::contentTypes['linkmeServerapiLinkmePost'][0])
    {
        $returnType = '\DcsServerBot\Model\LinkMeResponse';
        $request = $this->linkmeServerapiLinkmePostRequest($discord_id, $force, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'linkmeServerapiLinkmePost'
     *
     * @param  string $discord_id Discord user ID (snowflake) (required)
     * @param  bool|null $force Force the operation (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkmeServerapiLinkmePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function linkmeServerapiLinkmePostRequest($discord_id, $force = false, string $contentType = self::contentTypes['linkmeServerapiLinkmePost'][0])
    {

        // verify the required parameter 'discord_id' is set
        if ($discord_id === null || (is_array($discord_id) && count($discord_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $discord_id when calling linkmeServerapiLinkmePost'
            );
        }



        $resourcePath = '/serverapi/linkme';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'discord_id' => $discord_id,
            'force' => $force,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation playerSquadronsServerapiPlayerSquadronsPost
     *
     * Player Squadrons
     *
     * @param  string $nick nick (required)
     * @param  string|null $date date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\PlayerSquadron[]|\DcsServerBot\Model\HTTPValidationError
     */
    public function playerSquadronsServerapiPlayerSquadronsPost($nick, $date = null, string $contentType = self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'][0])
    {
        list($response) = $this->playerSquadronsServerapiPlayerSquadronsPostWithHttpInfo($nick, $date, $contentType);
        return $response;
    }

    /**
     * Operation playerSquadronsServerapiPlayerSquadronsPostWithHttpInfo
     *
     * Player Squadrons
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\PlayerSquadron[]|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function playerSquadronsServerapiPlayerSquadronsPostWithHttpInfo($nick, $date = null, string $contentType = self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'][0])
    {
        $request = $this->playerSquadronsServerapiPlayerSquadronsPostRequest($nick, $date, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\PlayerSquadron[]',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\PlayerSquadron[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\PlayerSquadron[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation playerSquadronsServerapiPlayerSquadronsPostAsync
     *
     * Player Squadrons
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function playerSquadronsServerapiPlayerSquadronsPostAsync($nick, $date = null, string $contentType = self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'][0])
    {
        return $this->playerSquadronsServerapiPlayerSquadronsPostAsyncWithHttpInfo($nick, $date, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation playerSquadronsServerapiPlayerSquadronsPostAsyncWithHttpInfo
     *
     * Player Squadrons
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function playerSquadronsServerapiPlayerSquadronsPostAsyncWithHttpInfo($nick, $date = null, string $contentType = self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'][0])
    {
        $returnType = '\DcsServerBot\Model\PlayerSquadron[]';
        $request = $this->playerSquadronsServerapiPlayerSquadronsPostRequest($nick, $date, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'playerSquadronsServerapiPlayerSquadronsPost'
     *
     * @param  string $nick (required)
     * @param  string|null $date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function playerSquadronsServerapiPlayerSquadronsPostRequest($nick, $date = null, string $contentType = self::contentTypes['playerSquadronsServerapiPlayerSquadronsPost'][0])
    {

        // verify the required parameter 'nick' is set
        if ($nick === null || (is_array($nick) && count($nick) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nick when calling playerSquadronsServerapiPlayerSquadronsPost'
            );
        }



        $resourcePath = '/serverapi/player_squadrons';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'nick' => $nick,
            'date' => $date,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation serversServerapiServersGet
     *
     * Server list
     *
     * @param  string|null $server_name server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serversServerapiServersGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\ServerInfo[]|\DcsServerBot\Model\HTTPValidationError
     */
    public function serversServerapiServersGet($server_name = null, string $contentType = self::contentTypes['serversServerapiServersGet'][0])
    {
        list($response) = $this->serversServerapiServersGetWithHttpInfo($server_name, $contentType);
        return $response;
    }

    /**
     * Operation serversServerapiServersGetWithHttpInfo
     *
     * Server list
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serversServerapiServersGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\ServerInfo[]|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function serversServerapiServersGetWithHttpInfo($server_name = null, string $contentType = self::contentTypes['serversServerapiServersGet'][0])
    {
        $request = $this->serversServerapiServersGetRequest($server_name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\ServerInfo[]',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\ServerInfo[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\ServerInfo[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation serversServerapiServersGetAsync
     *
     * Server list
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serversServerapiServersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function serversServerapiServersGetAsync($server_name = null, string $contentType = self::contentTypes['serversServerapiServersGet'][0])
    {
        return $this->serversServerapiServersGetAsyncWithHttpInfo($server_name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation serversServerapiServersGetAsyncWithHttpInfo
     *
     * Server list
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serversServerapiServersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function serversServerapiServersGetAsyncWithHttpInfo($server_name = null, string $contentType = self::contentTypes['serversServerapiServersGet'][0])
    {
        $returnType = '\DcsServerBot\Model\ServerInfo[]';
        $request = $this->serversServerapiServersGetRequest($server_name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'serversServerapiServersGet'
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serversServerapiServersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function serversServerapiServersGetRequest($server_name = null, string $contentType = self::contentTypes['serversServerapiServersGet'][0])
    {



        $resourcePath = '/serverapi/servers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $server_name,
            'server_name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation serverstatsServerapiServerstatsGet
     *
     * Server Statistics
     *
     * @param  string|null $server_name server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serverstatsServerapiServerstatsGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\ServerStats|\DcsServerBot\Model\HTTPValidationError
     */
    public function serverstatsServerapiServerstatsGet($server_name = null, string $contentType = self::contentTypes['serverstatsServerapiServerstatsGet'][0])
    {
        list($response) = $this->serverstatsServerapiServerstatsGetWithHttpInfo($server_name, $contentType);
        return $response;
    }

    /**
     * Operation serverstatsServerapiServerstatsGetWithHttpInfo
     *
     * Server Statistics
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serverstatsServerapiServerstatsGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\ServerStats|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function serverstatsServerapiServerstatsGetWithHttpInfo($server_name = null, string $contentType = self::contentTypes['serverstatsServerapiServerstatsGet'][0])
    {
        $request = $this->serverstatsServerapiServerstatsGetRequest($server_name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\ServerStats',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\ServerStats',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\ServerStats',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation serverstatsServerapiServerstatsGetAsync
     *
     * Server Statistics
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serverstatsServerapiServerstatsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function serverstatsServerapiServerstatsGetAsync($server_name = null, string $contentType = self::contentTypes['serverstatsServerapiServerstatsGet'][0])
    {
        return $this->serverstatsServerapiServerstatsGetAsyncWithHttpInfo($server_name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation serverstatsServerapiServerstatsGetAsyncWithHttpInfo
     *
     * Server Statistics
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serverstatsServerapiServerstatsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function serverstatsServerapiServerstatsGetAsyncWithHttpInfo($server_name = null, string $contentType = self::contentTypes['serverstatsServerapiServerstatsGet'][0])
    {
        $returnType = '\DcsServerBot\Model\ServerStats';
        $request = $this->serverstatsServerapiServerstatsGetRequest($server_name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'serverstatsServerapiServerstatsGet'
     *
     * @param  string|null $server_name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['serverstatsServerapiServerstatsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function serverstatsServerapiServerstatsGetRequest($server_name = null, string $contentType = self::contentTypes['serverstatsServerapiServerstatsGet'][0])
    {



        $resourcePath = '/serverapi/serverstats';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $server_name,
            'server_name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation squadronMembersServerapiSquadronMembersPost
     *
     * Squadron Members
     *
     * @param  string $name name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronMembersServerapiSquadronMembersPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\UserEntry[]|\DcsServerBot\Model\HTTPValidationError
     */
    public function squadronMembersServerapiSquadronMembersPost($name, string $contentType = self::contentTypes['squadronMembersServerapiSquadronMembersPost'][0])
    {
        list($response) = $this->squadronMembersServerapiSquadronMembersPostWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation squadronMembersServerapiSquadronMembersPostWithHttpInfo
     *
     * Squadron Members
     *
     * @param  string $name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronMembersServerapiSquadronMembersPost'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\UserEntry[]|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function squadronMembersServerapiSquadronMembersPostWithHttpInfo($name, string $contentType = self::contentTypes['squadronMembersServerapiSquadronMembersPost'][0])
    {
        $request = $this->squadronMembersServerapiSquadronMembersPostRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\UserEntry[]',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\UserEntry[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\UserEntry[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation squadronMembersServerapiSquadronMembersPostAsync
     *
     * Squadron Members
     *
     * @param  string $name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronMembersServerapiSquadronMembersPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function squadronMembersServerapiSquadronMembersPostAsync($name, string $contentType = self::contentTypes['squadronMembersServerapiSquadronMembersPost'][0])
    {
        return $this->squadronMembersServerapiSquadronMembersPostAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation squadronMembersServerapiSquadronMembersPostAsyncWithHttpInfo
     *
     * Squadron Members
     *
     * @param  string $name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronMembersServerapiSquadronMembersPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function squadronMembersServerapiSquadronMembersPostAsyncWithHttpInfo($name, string $contentType = self::contentTypes['squadronMembersServerapiSquadronMembersPost'][0])
    {
        $returnType = '\DcsServerBot\Model\UserEntry[]';
        $request = $this->squadronMembersServerapiSquadronMembersPostRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'squadronMembersServerapiSquadronMembersPost'
     *
     * @param  string $name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronMembersServerapiSquadronMembersPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function squadronMembersServerapiSquadronMembersPostRequest($name, string $contentType = self::contentTypes['squadronMembersServerapiSquadronMembersPost'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling squadronMembersServerapiSquadronMembersPost'
            );
        }


        $resourcePath = '/serverapi/squadron_members';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'name' => $name,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation squadronsServerapiSquadronsGet
     *
     * Squadron list
     *
     * @param  int|null $limit limit (optional)
     * @param  int|null $offset offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronsServerapiSquadronsGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DcsServerBot\Model\SquadronInfo[]|\DcsServerBot\Model\HTTPValidationError
     */
    public function squadronsServerapiSquadronsGet($limit = null, $offset = 0, string $contentType = self::contentTypes['squadronsServerapiSquadronsGet'][0])
    {
        list($response) = $this->squadronsServerapiSquadronsGetWithHttpInfo($limit, $offset, $contentType);
        return $response;
    }

    /**
     * Operation squadronsServerapiSquadronsGetWithHttpInfo
     *
     * Squadron list
     *
     * @param  int|null $limit (optional)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronsServerapiSquadronsGet'] to see the possible values for this operation
     *
     * @throws \DcsServerBot\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DcsServerBot\Model\SquadronInfo[]|\DcsServerBot\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function squadronsServerapiSquadronsGetWithHttpInfo($limit = null, $offset = 0, string $contentType = self::contentTypes['squadronsServerapiSquadronsGet'][0])
    {
        $request = $this->squadronsServerapiSquadronsGetRequest($limit, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\SquadronInfo[]',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\DcsServerBot\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\DcsServerBot\Model\SquadronInfo[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\SquadronInfo[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DcsServerBot\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation squadronsServerapiSquadronsGetAsync
     *
     * Squadron list
     *
     * @param  int|null $limit (optional)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronsServerapiSquadronsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function squadronsServerapiSquadronsGetAsync($limit = null, $offset = 0, string $contentType = self::contentTypes['squadronsServerapiSquadronsGet'][0])
    {
        return $this->squadronsServerapiSquadronsGetAsyncWithHttpInfo($limit, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation squadronsServerapiSquadronsGetAsyncWithHttpInfo
     *
     * Squadron list
     *
     * @param  int|null $limit (optional)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronsServerapiSquadronsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function squadronsServerapiSquadronsGetAsyncWithHttpInfo($limit = null, $offset = 0, string $contentType = self::contentTypes['squadronsServerapiSquadronsGet'][0])
    {
        $returnType = '\DcsServerBot\Model\SquadronInfo[]';
        $request = $this->squadronsServerapiSquadronsGetRequest($limit, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'squadronsServerapiSquadronsGet'
     *
     * @param  int|null $limit (optional)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['squadronsServerapiSquadronsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function squadronsServerapiSquadronsGetRequest($limit = null, $offset = 0, string $contentType = self::contentTypes['squadronsServerapiSquadronsGet'][0])
    {




        $resourcePath = '/serverapi/squadrons';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
