<?php
/**
 * Highscore
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Model;

use \ArrayAccess;
use \DcsServerBot\ObjectSerializer;

/**
 * Highscore Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Highscore implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Highscore';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'playtime' => '\DcsServerBot\Model\PlaytimeEntry[]',
        'air_targets' => '\DcsServerBot\Model\HighscoreEntry[]',
        'ships' => '\DcsServerBot\Model\HighscoreEntry[]',
        'air_defence' => '\DcsServerBot\Model\HighscoreEntry[]',
        'ground_targets' => '\DcsServerBot\Model\HighscoreEntry[]',
        'kd_ratio' => '\DcsServerBot\Model\HighscoreEntry[]',
        'pv_p_kd_ratio' => '\DcsServerBot\Model\HighscoreEntry[]',
        'most_efficient_killers' => '\DcsServerBot\Model\HighscoreEntry[]',
        'most_wasteful_pilots' => '\DcsServerBot\Model\HighscoreEntry[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'playtime' => null,
        'air_targets' => null,
        'ships' => null,
        'air_defence' => null,
        'ground_targets' => null,
        'kd_ratio' => null,
        'pv_p_kd_ratio' => null,
        'most_efficient_killers' => null,
        'most_wasteful_pilots' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'playtime' => false,
        'air_targets' => false,
        'ships' => false,
        'air_defence' => false,
        'ground_targets' => false,
        'kd_ratio' => false,
        'pv_p_kd_ratio' => false,
        'most_efficient_killers' => false,
        'most_wasteful_pilots' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'playtime' => 'playtime',
        'air_targets' => 'Air Targets',
        'ships' => 'Ships',
        'air_defence' => 'Air Defence',
        'ground_targets' => 'Ground Targets',
        'kd_ratio' => 'KD-Ratio',
        'pv_p_kd_ratio' => 'PvP-KD-Ratio',
        'most_efficient_killers' => 'Most Efficient Killers',
        'most_wasteful_pilots' => 'Most Wasteful Pilots'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'playtime' => 'setPlaytime',
        'air_targets' => 'setAirTargets',
        'ships' => 'setShips',
        'air_defence' => 'setAirDefence',
        'ground_targets' => 'setGroundTargets',
        'kd_ratio' => 'setKdRatio',
        'pv_p_kd_ratio' => 'setPvPKdRatio',
        'most_efficient_killers' => 'setMostEfficientKillers',
        'most_wasteful_pilots' => 'setMostWastefulPilots'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'playtime' => 'getPlaytime',
        'air_targets' => 'getAirTargets',
        'ships' => 'getShips',
        'air_defence' => 'getAirDefence',
        'ground_targets' => 'getGroundTargets',
        'kd_ratio' => 'getKdRatio',
        'pv_p_kd_ratio' => 'getPvPKdRatio',
        'most_efficient_killers' => 'getMostEfficientKillers',
        'most_wasteful_pilots' => 'getMostWastefulPilots'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('playtime', $data ?? [], null);
        $this->setIfExists('air_targets', $data ?? [], null);
        $this->setIfExists('ships', $data ?? [], null);
        $this->setIfExists('air_defence', $data ?? [], null);
        $this->setIfExists('ground_targets', $data ?? [], null);
        $this->setIfExists('kd_ratio', $data ?? [], null);
        $this->setIfExists('pv_p_kd_ratio', $data ?? [], null);
        $this->setIfExists('most_efficient_killers', $data ?? [], null);
        $this->setIfExists('most_wasteful_pilots', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets playtime
     *
     * @return \DcsServerBot\Model\PlaytimeEntry[]|null
     */
    public function getPlaytime()
    {
        return $this->container['playtime'];
    }

    /**
     * Sets playtime
     *
     * @param \DcsServerBot\Model\PlaytimeEntry[]|null $playtime Playtime rankings
     *
     * @return self
     */
    public function setPlaytime($playtime)
    {
        if (is_null($playtime)) {
            throw new \InvalidArgumentException('non-nullable playtime cannot be null');
        }
        $this->container['playtime'] = $playtime;

        return $this;
    }

    /**
     * Gets air_targets
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getAirTargets()
    {
        return $this->container['air_targets'];
    }

    /**
     * Sets air_targets
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $air_targets Air kills rankings
     *
     * @return self
     */
    public function setAirTargets($air_targets)
    {
        if (is_null($air_targets)) {
            throw new \InvalidArgumentException('non-nullable air_targets cannot be null');
        }
        $this->container['air_targets'] = $air_targets;

        return $this;
    }

    /**
     * Gets ships
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getShips()
    {
        return $this->container['ships'];
    }

    /**
     * Sets ships
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $ships Ship kills rankings
     *
     * @return self
     */
    public function setShips($ships)
    {
        if (is_null($ships)) {
            throw new \InvalidArgumentException('non-nullable ships cannot be null');
        }
        $this->container['ships'] = $ships;

        return $this;
    }

    /**
     * Gets air_defence
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getAirDefence()
    {
        return $this->container['air_defence'];
    }

    /**
     * Sets air_defence
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $air_defence SAM kills rankings
     *
     * @return self
     */
    public function setAirDefence($air_defence)
    {
        if (is_null($air_defence)) {
            throw new \InvalidArgumentException('non-nullable air_defence cannot be null');
        }
        $this->container['air_defence'] = $air_defence;

        return $this;
    }

    /**
     * Gets ground_targets
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getGroundTargets()
    {
        return $this->container['ground_targets'];
    }

    /**
     * Sets ground_targets
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $ground_targets Ground kills rankings
     *
     * @return self
     */
    public function setGroundTargets($ground_targets)
    {
        if (is_null($ground_targets)) {
            throw new \InvalidArgumentException('non-nullable ground_targets cannot be null');
        }
        $this->container['ground_targets'] = $ground_targets;

        return $this;
    }

    /**
     * Gets kd_ratio
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getKdRatio()
    {
        return $this->container['kd_ratio'];
    }

    /**
     * Sets kd_ratio
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $kd_ratio Kill/Death ratio rankings
     *
     * @return self
     */
    public function setKdRatio($kd_ratio)
    {
        if (is_null($kd_ratio)) {
            throw new \InvalidArgumentException('non-nullable kd_ratio cannot be null');
        }
        $this->container['kd_ratio'] = $kd_ratio;

        return $this;
    }

    /**
     * Gets pv_p_kd_ratio
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getPvPKdRatio()
    {
        return $this->container['pv_p_kd_ratio'];
    }

    /**
     * Sets pv_p_kd_ratio
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $pv_p_kd_ratio PvP Kill/Death ratio rankings
     *
     * @return self
     */
    public function setPvPKdRatio($pv_p_kd_ratio)
    {
        if (is_null($pv_p_kd_ratio)) {
            throw new \InvalidArgumentException('non-nullable pv_p_kd_ratio cannot be null');
        }
        $this->container['pv_p_kd_ratio'] = $pv_p_kd_ratio;

        return $this;
    }

    /**
     * Gets most_efficient_killers
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getMostEfficientKillers()
    {
        return $this->container['most_efficient_killers'];
    }

    /**
     * Sets most_efficient_killers
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $most_efficient_killers Kills per hour rankings
     *
     * @return self
     */
    public function setMostEfficientKillers($most_efficient_killers)
    {
        if (is_null($most_efficient_killers)) {
            throw new \InvalidArgumentException('non-nullable most_efficient_killers cannot be null');
        }
        $this->container['most_efficient_killers'] = $most_efficient_killers;

        return $this;
    }

    /**
     * Gets most_wasteful_pilots
     *
     * @return \DcsServerBot\Model\HighscoreEntry[]|null
     */
    public function getMostWastefulPilots()
    {
        return $this->container['most_wasteful_pilots'];
    }

    /**
     * Sets most_wasteful_pilots
     *
     * @param \DcsServerBot\Model\HighscoreEntry[]|null $most_wasteful_pilots Crashes per hour rankings
     *
     * @return self
     */
    public function setMostWastefulPilots($most_wasteful_pilots)
    {
        if (is_null($most_wasteful_pilots)) {
            throw new \InvalidArgumentException('non-nullable most_wasteful_pilots cannot be null');
        }
        $this->container['most_wasteful_pilots'] = $most_wasteful_pilots;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


