<?php
/**
 * PlayerStats
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Model;

use \ArrayAccess;
use \DcsServerBot\ObjectSerializer;

/**
 * PlayerStats Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PlayerStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PlayerStats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'playtime' => 'int',
        'kills' => 'int',
        'deaths' => 'int',
        'kills_pvp' => 'int',
        'deaths_pvp' => 'int',
        'kills_planes' => 'int',
        'kills_helicopters' => 'int',
        'kills_ships' => 'int',
        'kills_sams' => 'int',
        'kills_ground' => 'int',
        'deaths_planes' => 'int',
        'deaths_helicopters' => 'int',
        'deaths_ships' => 'int',
        'deaths_sams' => 'int',
        'deaths_ground' => 'int',
        'takeoffs' => 'int',
        'landings' => 'int',
        'ejections' => 'int',
        'crashes' => 'int',
        'teamkills' => 'int',
        'kdr' => 'string',
        'kdr_pvp' => 'string',
        'kills_by_module' => '\DcsServerBot\Model\ModuleStats[]',
        'kdr_by_module' => '\DcsServerBot\Model\ModuleStats[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'playtime' => null,
        'kills' => null,
        'deaths' => null,
        'kills_pvp' => null,
        'deaths_pvp' => null,
        'kills_planes' => null,
        'kills_helicopters' => null,
        'kills_ships' => null,
        'kills_sams' => null,
        'kills_ground' => null,
        'deaths_planes' => null,
        'deaths_helicopters' => null,
        'deaths_ships' => null,
        'deaths_sams' => null,
        'deaths_ground' => null,
        'takeoffs' => null,
        'landings' => null,
        'ejections' => null,
        'crashes' => null,
        'teamkills' => null,
        'kdr' => null,
        'kdr_pvp' => null,
        'kills_by_module' => null,
        'kdr_by_module' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'playtime' => false,
        'kills' => false,
        'deaths' => false,
        'kills_pvp' => false,
        'deaths_pvp' => false,
        'kills_planes' => false,
        'kills_helicopters' => false,
        'kills_ships' => false,
        'kills_sams' => false,
        'kills_ground' => false,
        'deaths_planes' => false,
        'deaths_helicopters' => false,
        'deaths_ships' => false,
        'deaths_sams' => false,
        'deaths_ground' => false,
        'takeoffs' => false,
        'landings' => false,
        'ejections' => false,
        'crashes' => false,
        'teamkills' => false,
        'kdr' => false,
        'kdr_pvp' => false,
        'kills_by_module' => false,
        'kdr_by_module' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'playtime' => 'playtime',
        'kills' => 'kills',
        'deaths' => 'deaths',
        'kills_pvp' => 'kills_pvp',
        'deaths_pvp' => 'deaths_pvp',
        'kills_planes' => 'kills_planes',
        'kills_helicopters' => 'kills_helicopters',
        'kills_ships' => 'kills_ships',
        'kills_sams' => 'kills_sams',
        'kills_ground' => 'kills_ground',
        'deaths_planes' => 'deaths_planes',
        'deaths_helicopters' => 'deaths_helicopters',
        'deaths_ships' => 'deaths_ships',
        'deaths_sams' => 'deaths_sams',
        'deaths_ground' => 'deaths_ground',
        'takeoffs' => 'takeoffs',
        'landings' => 'landings',
        'ejections' => 'ejections',
        'crashes' => 'crashes',
        'teamkills' => 'teamkills',
        'kdr' => 'kdr',
        'kdr_pvp' => 'kdr_pvp',
        'kills_by_module' => 'killsByModule',
        'kdr_by_module' => 'kdrByModule'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'playtime' => 'setPlaytime',
        'kills' => 'setKills',
        'deaths' => 'setDeaths',
        'kills_pvp' => 'setKillsPvp',
        'deaths_pvp' => 'setDeathsPvp',
        'kills_planes' => 'setKillsPlanes',
        'kills_helicopters' => 'setKillsHelicopters',
        'kills_ships' => 'setKillsShips',
        'kills_sams' => 'setKillsSams',
        'kills_ground' => 'setKillsGround',
        'deaths_planes' => 'setDeathsPlanes',
        'deaths_helicopters' => 'setDeathsHelicopters',
        'deaths_ships' => 'setDeathsShips',
        'deaths_sams' => 'setDeathsSams',
        'deaths_ground' => 'setDeathsGround',
        'takeoffs' => 'setTakeoffs',
        'landings' => 'setLandings',
        'ejections' => 'setEjections',
        'crashes' => 'setCrashes',
        'teamkills' => 'setTeamkills',
        'kdr' => 'setKdr',
        'kdr_pvp' => 'setKdrPvp',
        'kills_by_module' => 'setKillsByModule',
        'kdr_by_module' => 'setKdrByModule'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'playtime' => 'getPlaytime',
        'kills' => 'getKills',
        'deaths' => 'getDeaths',
        'kills_pvp' => 'getKillsPvp',
        'deaths_pvp' => 'getDeathsPvp',
        'kills_planes' => 'getKillsPlanes',
        'kills_helicopters' => 'getKillsHelicopters',
        'kills_ships' => 'getKillsShips',
        'kills_sams' => 'getKillsSams',
        'kills_ground' => 'getKillsGround',
        'deaths_planes' => 'getDeathsPlanes',
        'deaths_helicopters' => 'getDeathsHelicopters',
        'deaths_ships' => 'getDeathsShips',
        'deaths_sams' => 'getDeathsSams',
        'deaths_ground' => 'getDeathsGround',
        'takeoffs' => 'getTakeoffs',
        'landings' => 'getLandings',
        'ejections' => 'getEjections',
        'crashes' => 'getCrashes',
        'teamkills' => 'getTeamkills',
        'kdr' => 'getKdr',
        'kdr_pvp' => 'getKdrPvp',
        'kills_by_module' => 'getKillsByModule',
        'kdr_by_module' => 'getKdrByModule'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('playtime', $data ?? [], null);
        $this->setIfExists('kills', $data ?? [], null);
        $this->setIfExists('deaths', $data ?? [], null);
        $this->setIfExists('kills_pvp', $data ?? [], null);
        $this->setIfExists('deaths_pvp', $data ?? [], null);
        $this->setIfExists('kills_planes', $data ?? [], null);
        $this->setIfExists('kills_helicopters', $data ?? [], null);
        $this->setIfExists('kills_ships', $data ?? [], null);
        $this->setIfExists('kills_sams', $data ?? [], null);
        $this->setIfExists('kills_ground', $data ?? [], null);
        $this->setIfExists('deaths_planes', $data ?? [], null);
        $this->setIfExists('deaths_helicopters', $data ?? [], null);
        $this->setIfExists('deaths_ships', $data ?? [], null);
        $this->setIfExists('deaths_sams', $data ?? [], null);
        $this->setIfExists('deaths_ground', $data ?? [], null);
        $this->setIfExists('takeoffs', $data ?? [], null);
        $this->setIfExists('landings', $data ?? [], null);
        $this->setIfExists('ejections', $data ?? [], null);
        $this->setIfExists('crashes', $data ?? [], null);
        $this->setIfExists('teamkills', $data ?? [], null);
        $this->setIfExists('kdr', $data ?? [], null);
        $this->setIfExists('kdr_pvp', $data ?? [], null);
        $this->setIfExists('kills_by_module', $data ?? [], null);
        $this->setIfExists('kdr_by_module', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['playtime'] === null) {
            $invalidProperties[] = "'playtime' can't be null";
        }
        if ($this->container['kills'] === null) {
            $invalidProperties[] = "'kills' can't be null";
        }
        if ($this->container['deaths'] === null) {
            $invalidProperties[] = "'deaths' can't be null";
        }
        if ($this->container['kills_pvp'] === null) {
            $invalidProperties[] = "'kills_pvp' can't be null";
        }
        if ($this->container['deaths_pvp'] === null) {
            $invalidProperties[] = "'deaths_pvp' can't be null";
        }
        if ($this->container['kills_planes'] === null) {
            $invalidProperties[] = "'kills_planes' can't be null";
        }
        if ($this->container['kills_helicopters'] === null) {
            $invalidProperties[] = "'kills_helicopters' can't be null";
        }
        if ($this->container['kills_ships'] === null) {
            $invalidProperties[] = "'kills_ships' can't be null";
        }
        if ($this->container['kills_sams'] === null) {
            $invalidProperties[] = "'kills_sams' can't be null";
        }
        if ($this->container['kills_ground'] === null) {
            $invalidProperties[] = "'kills_ground' can't be null";
        }
        if ($this->container['deaths_planes'] === null) {
            $invalidProperties[] = "'deaths_planes' can't be null";
        }
        if ($this->container['deaths_helicopters'] === null) {
            $invalidProperties[] = "'deaths_helicopters' can't be null";
        }
        if ($this->container['deaths_ships'] === null) {
            $invalidProperties[] = "'deaths_ships' can't be null";
        }
        if ($this->container['deaths_sams'] === null) {
            $invalidProperties[] = "'deaths_sams' can't be null";
        }
        if ($this->container['deaths_ground'] === null) {
            $invalidProperties[] = "'deaths_ground' can't be null";
        }
        if ($this->container['takeoffs'] === null) {
            $invalidProperties[] = "'takeoffs' can't be null";
        }
        if ($this->container['landings'] === null) {
            $invalidProperties[] = "'landings' can't be null";
        }
        if ($this->container['ejections'] === null) {
            $invalidProperties[] = "'ejections' can't be null";
        }
        if ($this->container['crashes'] === null) {
            $invalidProperties[] = "'crashes' can't be null";
        }
        if ($this->container['teamkills'] === null) {
            $invalidProperties[] = "'teamkills' can't be null";
        }
        if ($this->container['kdr'] === null) {
            $invalidProperties[] = "'kdr' can't be null";
        }
        if (!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", $this->container['kdr'])) {
            $invalidProperties[] = "invalid value for 'kdr', must be conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.";
        }

        if ($this->container['kdr_pvp'] === null) {
            $invalidProperties[] = "'kdr_pvp' can't be null";
        }
        if (!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", $this->container['kdr_pvp'])) {
            $invalidProperties[] = "invalid value for 'kdr_pvp', must be conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets playtime
     *
     * @return int
     */
    public function getPlaytime()
    {
        return $this->container['playtime'];
    }

    /**
     * Sets playtime
     *
     * @param int $playtime Total playtime in seconds
     *
     * @return self
     */
    public function setPlaytime($playtime)
    {
        if (is_null($playtime)) {
            throw new \InvalidArgumentException('non-nullable playtime cannot be null');
        }
        $this->container['playtime'] = $playtime;

        return $this;
    }

    /**
     * Gets kills
     *
     * @return int
     */
    public function getKills()
    {
        return $this->container['kills'];
    }

    /**
     * Sets kills
     *
     * @param int $kills Total kills
     *
     * @return self
     */
    public function setKills($kills)
    {
        if (is_null($kills)) {
            throw new \InvalidArgumentException('non-nullable kills cannot be null');
        }
        $this->container['kills'] = $kills;

        return $this;
    }

    /**
     * Gets deaths
     *
     * @return int
     */
    public function getDeaths()
    {
        return $this->container['deaths'];
    }

    /**
     * Sets deaths
     *
     * @param int $deaths Total deaths
     *
     * @return self
     */
    public function setDeaths($deaths)
    {
        if (is_null($deaths)) {
            throw new \InvalidArgumentException('non-nullable deaths cannot be null');
        }
        $this->container['deaths'] = $deaths;

        return $this;
    }

    /**
     * Gets kills_pvp
     *
     * @return int
     */
    public function getKillsPvp()
    {
        return $this->container['kills_pvp'];
    }

    /**
     * Sets kills_pvp
     *
     * @param int $kills_pvp Total PvP kills
     *
     * @return self
     */
    public function setKillsPvp($kills_pvp)
    {
        if (is_null($kills_pvp)) {
            throw new \InvalidArgumentException('non-nullable kills_pvp cannot be null');
        }
        $this->container['kills_pvp'] = $kills_pvp;

        return $this;
    }

    /**
     * Gets deaths_pvp
     *
     * @return int
     */
    public function getDeathsPvp()
    {
        return $this->container['deaths_pvp'];
    }

    /**
     * Sets deaths_pvp
     *
     * @param int $deaths_pvp Total PvP deaths
     *
     * @return self
     */
    public function setDeathsPvp($deaths_pvp)
    {
        if (is_null($deaths_pvp)) {
            throw new \InvalidArgumentException('non-nullable deaths_pvp cannot be null');
        }
        $this->container['deaths_pvp'] = $deaths_pvp;

        return $this;
    }

    /**
     * Gets kills_planes
     *
     * @return int
     */
    public function getKillsPlanes()
    {
        return $this->container['kills_planes'];
    }

    /**
     * Sets kills_planes
     *
     * @param int $kills_planes Total plane kills
     *
     * @return self
     */
    public function setKillsPlanes($kills_planes)
    {
        if (is_null($kills_planes)) {
            throw new \InvalidArgumentException('non-nullable kills_planes cannot be null');
        }
        $this->container['kills_planes'] = $kills_planes;

        return $this;
    }

    /**
     * Gets kills_helicopters
     *
     * @return int
     */
    public function getKillsHelicopters()
    {
        return $this->container['kills_helicopters'];
    }

    /**
     * Sets kills_helicopters
     *
     * @param int $kills_helicopters Total helicopter kills
     *
     * @return self
     */
    public function setKillsHelicopters($kills_helicopters)
    {
        if (is_null($kills_helicopters)) {
            throw new \InvalidArgumentException('non-nullable kills_helicopters cannot be null');
        }
        $this->container['kills_helicopters'] = $kills_helicopters;

        return $this;
    }

    /**
     * Gets kills_ships
     *
     * @return int
     */
    public function getKillsShips()
    {
        return $this->container['kills_ships'];
    }

    /**
     * Sets kills_ships
     *
     * @param int $kills_ships Total ship kills
     *
     * @return self
     */
    public function setKillsShips($kills_ships)
    {
        if (is_null($kills_ships)) {
            throw new \InvalidArgumentException('non-nullable kills_ships cannot be null');
        }
        $this->container['kills_ships'] = $kills_ships;

        return $this;
    }

    /**
     * Gets kills_sams
     *
     * @return int
     */
    public function getKillsSams()
    {
        return $this->container['kills_sams'];
    }

    /**
     * Sets kills_sams
     *
     * @param int $kills_sams Total SAM kills
     *
     * @return self
     */
    public function setKillsSams($kills_sams)
    {
        if (is_null($kills_sams)) {
            throw new \InvalidArgumentException('non-nullable kills_sams cannot be null');
        }
        $this->container['kills_sams'] = $kills_sams;

        return $this;
    }

    /**
     * Gets kills_ground
     *
     * @return int
     */
    public function getKillsGround()
    {
        return $this->container['kills_ground'];
    }

    /**
     * Sets kills_ground
     *
     * @param int $kills_ground Total ground kills
     *
     * @return self
     */
    public function setKillsGround($kills_ground)
    {
        if (is_null($kills_ground)) {
            throw new \InvalidArgumentException('non-nullable kills_ground cannot be null');
        }
        $this->container['kills_ground'] = $kills_ground;

        return $this;
    }

    /**
     * Gets deaths_planes
     *
     * @return int
     */
    public function getDeathsPlanes()
    {
        return $this->container['deaths_planes'];
    }

    /**
     * Sets deaths_planes
     *
     * @param int $deaths_planes Total plane deaths
     *
     * @return self
     */
    public function setDeathsPlanes($deaths_planes)
    {
        if (is_null($deaths_planes)) {
            throw new \InvalidArgumentException('non-nullable deaths_planes cannot be null');
        }
        $this->container['deaths_planes'] = $deaths_planes;

        return $this;
    }

    /**
     * Gets deaths_helicopters
     *
     * @return int
     */
    public function getDeathsHelicopters()
    {
        return $this->container['deaths_helicopters'];
    }

    /**
     * Sets deaths_helicopters
     *
     * @param int $deaths_helicopters Total helicopter deaths
     *
     * @return self
     */
    public function setDeathsHelicopters($deaths_helicopters)
    {
        if (is_null($deaths_helicopters)) {
            throw new \InvalidArgumentException('non-nullable deaths_helicopters cannot be null');
        }
        $this->container['deaths_helicopters'] = $deaths_helicopters;

        return $this;
    }

    /**
     * Gets deaths_ships
     *
     * @return int
     */
    public function getDeathsShips()
    {
        return $this->container['deaths_ships'];
    }

    /**
     * Sets deaths_ships
     *
     * @param int $deaths_ships Total ship deaths
     *
     * @return self
     */
    public function setDeathsShips($deaths_ships)
    {
        if (is_null($deaths_ships)) {
            throw new \InvalidArgumentException('non-nullable deaths_ships cannot be null');
        }
        $this->container['deaths_ships'] = $deaths_ships;

        return $this;
    }

    /**
     * Gets deaths_sams
     *
     * @return int
     */
    public function getDeathsSams()
    {
        return $this->container['deaths_sams'];
    }

    /**
     * Sets deaths_sams
     *
     * @param int $deaths_sams Total SAM deaths
     *
     * @return self
     */
    public function setDeathsSams($deaths_sams)
    {
        if (is_null($deaths_sams)) {
            throw new \InvalidArgumentException('non-nullable deaths_sams cannot be null');
        }
        $this->container['deaths_sams'] = $deaths_sams;

        return $this;
    }

    /**
     * Gets deaths_ground
     *
     * @return int
     */
    public function getDeathsGround()
    {
        return $this->container['deaths_ground'];
    }

    /**
     * Sets deaths_ground
     *
     * @param int $deaths_ground Total ground deaths
     *
     * @return self
     */
    public function setDeathsGround($deaths_ground)
    {
        if (is_null($deaths_ground)) {
            throw new \InvalidArgumentException('non-nullable deaths_ground cannot be null');
        }
        $this->container['deaths_ground'] = $deaths_ground;

        return $this;
    }

    /**
     * Gets takeoffs
     *
     * @return int
     */
    public function getTakeoffs()
    {
        return $this->container['takeoffs'];
    }

    /**
     * Sets takeoffs
     *
     * @param int $takeoffs Number of takeoffs
     *
     * @return self
     */
    public function setTakeoffs($takeoffs)
    {
        if (is_null($takeoffs)) {
            throw new \InvalidArgumentException('non-nullable takeoffs cannot be null');
        }
        $this->container['takeoffs'] = $takeoffs;

        return $this;
    }

    /**
     * Gets landings
     *
     * @return int
     */
    public function getLandings()
    {
        return $this->container['landings'];
    }

    /**
     * Sets landings
     *
     * @param int $landings Number of landings
     *
     * @return self
     */
    public function setLandings($landings)
    {
        if (is_null($landings)) {
            throw new \InvalidArgumentException('non-nullable landings cannot be null');
        }
        $this->container['landings'] = $landings;

        return $this;
    }

    /**
     * Gets ejections
     *
     * @return int
     */
    public function getEjections()
    {
        return $this->container['ejections'];
    }

    /**
     * Sets ejections
     *
     * @param int $ejections Number of ejections
     *
     * @return self
     */
    public function setEjections($ejections)
    {
        if (is_null($ejections)) {
            throw new \InvalidArgumentException('non-nullable ejections cannot be null');
        }
        $this->container['ejections'] = $ejections;

        return $this;
    }

    /**
     * Gets crashes
     *
     * @return int
     */
    public function getCrashes()
    {
        return $this->container['crashes'];
    }

    /**
     * Sets crashes
     *
     * @param int $crashes Number of crashes
     *
     * @return self
     */
    public function setCrashes($crashes)
    {
        if (is_null($crashes)) {
            throw new \InvalidArgumentException('non-nullable crashes cannot be null');
        }
        $this->container['crashes'] = $crashes;

        return $this;
    }

    /**
     * Gets teamkills
     *
     * @return int
     */
    public function getTeamkills()
    {
        return $this->container['teamkills'];
    }

    /**
     * Sets teamkills
     *
     * @param int $teamkills Number of team kills
     *
     * @return self
     */
    public function setTeamkills($teamkills)
    {
        if (is_null($teamkills)) {
            throw new \InvalidArgumentException('non-nullable teamkills cannot be null');
        }
        $this->container['teamkills'] = $teamkills;

        return $this;
    }

    /**
     * Gets kdr
     *
     * @return string
     */
    public function getKdr()
    {
        return $this->container['kdr'];
    }

    /**
     * Sets kdr
     *
     * @param string $kdr Kill/death ratio
     *
     * @return self
     */
    public function setKdr($kdr)
    {
        if (is_null($kdr)) {
            throw new \InvalidArgumentException('non-nullable kdr cannot be null');
        }

        if ((!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", ObjectSerializer::toString($kdr)))) {
            throw new \InvalidArgumentException("invalid value for \$kdr when calling PlayerStats., must conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.");
        }

        $this->container['kdr'] = $kdr;

        return $this;
    }

    /**
     * Gets kdr_pvp
     *
     * @return string
     */
    public function getKdrPvp()
    {
        return $this->container['kdr_pvp'];
    }

    /**
     * Sets kdr_pvp
     *
     * @param string $kdr_pvp PvP Kill/death ratio
     *
     * @return self
     */
    public function setKdrPvp($kdr_pvp)
    {
        if (is_null($kdr_pvp)) {
            throw new \InvalidArgumentException('non-nullable kdr_pvp cannot be null');
        }

        if ((!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", ObjectSerializer::toString($kdr_pvp)))) {
            throw new \InvalidArgumentException("invalid value for \$kdr_pvp when calling PlayerStats., must conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.");
        }

        $this->container['kdr_pvp'] = $kdr_pvp;

        return $this;
    }

    /**
     * Gets kills_by_module
     *
     * @return \DcsServerBot\Model\ModuleStats[]|null
     */
    public function getKillsByModule()
    {
        return $this->container['kills_by_module'];
    }

    /**
     * Sets kills_by_module
     *
     * @param \DcsServerBot\Model\ModuleStats[]|null $kills_by_module PvP-Kills breakdown by module
     *
     * @return self
     */
    public function setKillsByModule($kills_by_module)
    {
        if (is_null($kills_by_module)) {
            throw new \InvalidArgumentException('non-nullable kills_by_module cannot be null');
        }
        $this->container['kills_by_module'] = $kills_by_module;

        return $this;
    }

    /**
     * Gets kdr_by_module
     *
     * @return \DcsServerBot\Model\ModuleStats[]|null
     */
    public function getKdrByModule()
    {
        return $this->container['kdr_by_module'];
    }

    /**
     * Sets kdr_by_module
     *
     * @param \DcsServerBot\Model\ModuleStats[]|null $kdr_by_module PvP-KDR breakdown by module
     *
     * @return self
     */
    public function setKdrByModule($kdr_by_module)
    {
        if (is_null($kdr_by_module)) {
            throw new \InvalidArgumentException('non-nullable kdr_by_module cannot be null');
        }
        $this->container['kdr_by_module'] = $kdr_by_module;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


