<?php
/**
 * PlayerInfo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Model;

use \ArrayAccess;
use \DcsServerBot\ObjectSerializer;

/**
 * PlayerInfo Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PlayerInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PlayerInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'current_server' => 'string',
        'overall' => '\DcsServerBot\Model\PlayerStats',
        'last_session' => '\DcsServerBot\Model\PlayerStats',
        'module_stats' => '\DcsServerBot\Model\ModuleStats[]',
        'credits' => '\DcsServerBot\Model\CampaignCredits',
        'squadrons' => '\DcsServerBot\Model\PlayerSquadron[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'current_server' => null,
        'overall' => null,
        'last_session' => null,
        'module_stats' => null,
        'credits' => null,
        'squadrons' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'current_server' => true,
        'overall' => false,
        'last_session' => false,
        'module_stats' => false,
        'credits' => true,
        'squadrons' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current_server' => 'current_server',
        'overall' => 'overall',
        'last_session' => 'last_session',
        'module_stats' => 'module_stats',
        'credits' => 'credits',
        'squadrons' => 'squadrons'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current_server' => 'setCurrentServer',
        'overall' => 'setOverall',
        'last_session' => 'setLastSession',
        'module_stats' => 'setModuleStats',
        'credits' => 'setCredits',
        'squadrons' => 'setSquadrons'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current_server' => 'getCurrentServer',
        'overall' => 'getOverall',
        'last_session' => 'getLastSession',
        'module_stats' => 'getModuleStats',
        'credits' => 'getCredits',
        'squadrons' => 'getSquadrons'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('current_server', $data ?? [], null);
        $this->setIfExists('overall', $data ?? [], null);
        $this->setIfExists('last_session', $data ?? [], null);
        $this->setIfExists('module_stats', $data ?? [], null);
        $this->setIfExists('credits', $data ?? [], null);
        $this->setIfExists('squadrons', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['overall'] === null) {
            $invalidProperties[] = "'overall' can't be null";
        }
        if ($this->container['last_session'] === null) {
            $invalidProperties[] = "'last_session' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current_server
     *
     * @return string|null
     */
    public function getCurrentServer()
    {
        return $this->container['current_server'];
    }

    /**
     * Sets current_server
     *
     * @param string|null $current_server current_server
     *
     * @return self
     */
    public function setCurrentServer($current_server)
    {
        if (is_null($current_server)) {
            array_push($this->openAPINullablesSetToNull, 'current_server');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('current_server', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['current_server'] = $current_server;

        return $this;
    }

    /**
     * Gets overall
     *
     * @return \DcsServerBot\Model\PlayerStats
     */
    public function getOverall()
    {
        return $this->container['overall'];
    }

    /**
     * Sets overall
     *
     * @param \DcsServerBot\Model\PlayerStats $overall Overall statistics
     *
     * @return self
     */
    public function setOverall($overall)
    {
        if (is_null($overall)) {
            throw new \InvalidArgumentException('non-nullable overall cannot be null');
        }
        $this->container['overall'] = $overall;

        return $this;
    }

    /**
     * Gets last_session
     *
     * @return \DcsServerBot\Model\PlayerStats
     */
    public function getLastSession()
    {
        return $this->container['last_session'];
    }

    /**
     * Sets last_session
     *
     * @param \DcsServerBot\Model\PlayerStats $last_session Statistics of the last session
     *
     * @return self
     */
    public function setLastSession($last_session)
    {
        if (is_null($last_session)) {
            throw new \InvalidArgumentException('non-nullable last_session cannot be null');
        }
        $this->container['last_session'] = $last_session;

        return $this;
    }

    /**
     * Gets module_stats
     *
     * @return \DcsServerBot\Model\ModuleStats[]|null
     */
    public function getModuleStats()
    {
        return $this->container['module_stats'];
    }

    /**
     * Sets module_stats
     *
     * @param \DcsServerBot\Model\ModuleStats[]|null $module_stats Statistics by module
     *
     * @return self
     */
    public function setModuleStats($module_stats)
    {
        if (is_null($module_stats)) {
            throw new \InvalidArgumentException('non-nullable module_stats cannot be null');
        }
        $this->container['module_stats'] = $module_stats;

        return $this;
    }

    /**
     * Gets credits
     *
     * @return \DcsServerBot\Model\CampaignCredits|null
     */
    public function getCredits()
    {
        return $this->container['credits'];
    }

    /**
     * Sets credits
     *
     * @param \DcsServerBot\Model\CampaignCredits|null $credits credits
     *
     * @return self
     */
    public function setCredits($credits)
    {
        if (is_null($credits)) {
            array_push($this->openAPINullablesSetToNull, 'credits');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('credits', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['credits'] = $credits;

        return $this;
    }

    /**
     * Gets squadrons
     *
     * @return \DcsServerBot\Model\PlayerSquadron[]|null
     */
    public function getSquadrons()
    {
        return $this->container['squadrons'];
    }

    /**
     * Sets squadrons
     *
     * @param \DcsServerBot\Model\PlayerSquadron[]|null $squadrons Squadrons the player is a member of
     *
     * @return self
     */
    public function setSquadrons($squadrons)
    {
        if (is_null($squadrons)) {
            throw new \InvalidArgumentException('non-nullable squadrons cannot be null');
        }
        $this->container['squadrons'] = $squadrons;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


