<?php
/**
 * ServerAttendanceStats
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Model;

use \ArrayAccess;
use \DcsServerBot\ObjectSerializer;

/**
 * ServerAttendanceStats Class Doc Comment
 *
 * @category Class
 * @description Server attendance statistics using monitoring plugin patterns
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServerAttendanceStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServerAttendanceStats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'current_players' => 'int',
        'unique_players_24h' => 'int',
        'total_playtime_hours_24h' => 'float',
        'discord_members_24h' => 'int',
        'unique_players_7d' => 'int',
        'total_playtime_hours_7d' => 'float',
        'discord_members_7d' => 'int',
        'unique_players_30d' => 'int',
        'total_playtime_hours_30d' => 'float',
        'discord_members_30d' => 'int',
        'daily_trend' => 'array<string,mixed>[]',
        'top_theatres' => '\DcsServerBot\Model\TopTheatre[]',
        'top_missions' => '\DcsServerBot\Model\TopMission[]',
        'top_modules' => '\DcsServerBot\Model\TopModule[]',
        'total_sorties' => 'int',
        'total_kills' => 'int',
        'total_deaths' => 'int',
        'total_pvp_kills' => 'int',
        'total_pvp_deaths' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'current_players' => null,
        'unique_players_24h' => null,
        'total_playtime_hours_24h' => null,
        'discord_members_24h' => null,
        'unique_players_7d' => null,
        'total_playtime_hours_7d' => null,
        'discord_members_7d' => null,
        'unique_players_30d' => null,
        'total_playtime_hours_30d' => null,
        'discord_members_30d' => null,
        'daily_trend' => null,
        'top_theatres' => null,
        'top_missions' => null,
        'top_modules' => null,
        'total_sorties' => null,
        'total_kills' => null,
        'total_deaths' => null,
        'total_pvp_kills' => null,
        'total_pvp_deaths' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'current_players' => false,
        'unique_players_24h' => false,
        'total_playtime_hours_24h' => false,
        'discord_members_24h' => false,
        'unique_players_7d' => false,
        'total_playtime_hours_7d' => false,
        'discord_members_7d' => false,
        'unique_players_30d' => false,
        'total_playtime_hours_30d' => false,
        'discord_members_30d' => false,
        'daily_trend' => false,
        'top_theatres' => false,
        'top_missions' => false,
        'top_modules' => false,
        'total_sorties' => true,
        'total_kills' => true,
        'total_deaths' => true,
        'total_pvp_kills' => true,
        'total_pvp_deaths' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current_players' => 'current_players',
        'unique_players_24h' => 'unique_players_24h',
        'total_playtime_hours_24h' => 'total_playtime_hours_24h',
        'discord_members_24h' => 'discord_members_24h',
        'unique_players_7d' => 'unique_players_7d',
        'total_playtime_hours_7d' => 'total_playtime_hours_7d',
        'discord_members_7d' => 'discord_members_7d',
        'unique_players_30d' => 'unique_players_30d',
        'total_playtime_hours_30d' => 'total_playtime_hours_30d',
        'discord_members_30d' => 'discord_members_30d',
        'daily_trend' => 'daily_trend',
        'top_theatres' => 'top_theatres',
        'top_missions' => 'top_missions',
        'top_modules' => 'top_modules',
        'total_sorties' => 'total_sorties',
        'total_kills' => 'total_kills',
        'total_deaths' => 'total_deaths',
        'total_pvp_kills' => 'total_pvp_kills',
        'total_pvp_deaths' => 'total_pvp_deaths'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current_players' => 'setCurrentPlayers',
        'unique_players_24h' => 'setUniquePlayers24h',
        'total_playtime_hours_24h' => 'setTotalPlaytimeHours24h',
        'discord_members_24h' => 'setDiscordMembers24h',
        'unique_players_7d' => 'setUniquePlayers7d',
        'total_playtime_hours_7d' => 'setTotalPlaytimeHours7d',
        'discord_members_7d' => 'setDiscordMembers7d',
        'unique_players_30d' => 'setUniquePlayers30d',
        'total_playtime_hours_30d' => 'setTotalPlaytimeHours30d',
        'discord_members_30d' => 'setDiscordMembers30d',
        'daily_trend' => 'setDailyTrend',
        'top_theatres' => 'setTopTheatres',
        'top_missions' => 'setTopMissions',
        'top_modules' => 'setTopModules',
        'total_sorties' => 'setTotalSorties',
        'total_kills' => 'setTotalKills',
        'total_deaths' => 'setTotalDeaths',
        'total_pvp_kills' => 'setTotalPvpKills',
        'total_pvp_deaths' => 'setTotalPvpDeaths'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current_players' => 'getCurrentPlayers',
        'unique_players_24h' => 'getUniquePlayers24h',
        'total_playtime_hours_24h' => 'getTotalPlaytimeHours24h',
        'discord_members_24h' => 'getDiscordMembers24h',
        'unique_players_7d' => 'getUniquePlayers7d',
        'total_playtime_hours_7d' => 'getTotalPlaytimeHours7d',
        'discord_members_7d' => 'getDiscordMembers7d',
        'unique_players_30d' => 'getUniquePlayers30d',
        'total_playtime_hours_30d' => 'getTotalPlaytimeHours30d',
        'discord_members_30d' => 'getDiscordMembers30d',
        'daily_trend' => 'getDailyTrend',
        'top_theatres' => 'getTopTheatres',
        'top_missions' => 'getTopMissions',
        'top_modules' => 'getTopModules',
        'total_sorties' => 'getTotalSorties',
        'total_kills' => 'getTotalKills',
        'total_deaths' => 'getTotalDeaths',
        'total_pvp_kills' => 'getTotalPvpKills',
        'total_pvp_deaths' => 'getTotalPvpDeaths'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('current_players', $data ?? [], null);
        $this->setIfExists('unique_players_24h', $data ?? [], null);
        $this->setIfExists('total_playtime_hours_24h', $data ?? [], null);
        $this->setIfExists('discord_members_24h', $data ?? [], null);
        $this->setIfExists('unique_players_7d', $data ?? [], null);
        $this->setIfExists('total_playtime_hours_7d', $data ?? [], null);
        $this->setIfExists('discord_members_7d', $data ?? [], null);
        $this->setIfExists('unique_players_30d', $data ?? [], null);
        $this->setIfExists('total_playtime_hours_30d', $data ?? [], null);
        $this->setIfExists('discord_members_30d', $data ?? [], null);
        $this->setIfExists('daily_trend', $data ?? [], null);
        $this->setIfExists('top_theatres', $data ?? [], null);
        $this->setIfExists('top_missions', $data ?? [], null);
        $this->setIfExists('top_modules', $data ?? [], null);
        $this->setIfExists('total_sorties', $data ?? [], null);
        $this->setIfExists('total_kills', $data ?? [], null);
        $this->setIfExists('total_deaths', $data ?? [], null);
        $this->setIfExists('total_pvp_kills', $data ?? [], null);
        $this->setIfExists('total_pvp_deaths', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['current_players'] === null) {
            $invalidProperties[] = "'current_players' can't be null";
        }
        if ($this->container['unique_players_24h'] === null) {
            $invalidProperties[] = "'unique_players_24h' can't be null";
        }
        if ($this->container['total_playtime_hours_24h'] === null) {
            $invalidProperties[] = "'total_playtime_hours_24h' can't be null";
        }
        if ($this->container['discord_members_24h'] === null) {
            $invalidProperties[] = "'discord_members_24h' can't be null";
        }
        if ($this->container['unique_players_7d'] === null) {
            $invalidProperties[] = "'unique_players_7d' can't be null";
        }
        if ($this->container['total_playtime_hours_7d'] === null) {
            $invalidProperties[] = "'total_playtime_hours_7d' can't be null";
        }
        if ($this->container['discord_members_7d'] === null) {
            $invalidProperties[] = "'discord_members_7d' can't be null";
        }
        if ($this->container['unique_players_30d'] === null) {
            $invalidProperties[] = "'unique_players_30d' can't be null";
        }
        if ($this->container['total_playtime_hours_30d'] === null) {
            $invalidProperties[] = "'total_playtime_hours_30d' can't be null";
        }
        if ($this->container['discord_members_30d'] === null) {
            $invalidProperties[] = "'discord_members_30d' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current_players
     *
     * @return int
     */
    public function getCurrentPlayers()
    {
        return $this->container['current_players'];
    }

    /**
     * Sets current_players
     *
     * @param int $current_players Current number of active players
     *
     * @return self
     */
    public function setCurrentPlayers($current_players)
    {
        if (is_null($current_players)) {
            throw new \InvalidArgumentException('non-nullable current_players cannot be null');
        }
        $this->container['current_players'] = $current_players;

        return $this;
    }

    /**
     * Gets unique_players_24h
     *
     * @return int
     */
    public function getUniquePlayers24h()
    {
        return $this->container['unique_players_24h'];
    }

    /**
     * Sets unique_players_24h
     *
     * @param int $unique_players_24h Unique players in last 24 hours
     *
     * @return self
     */
    public function setUniquePlayers24h($unique_players_24h)
    {
        if (is_null($unique_players_24h)) {
            throw new \InvalidArgumentException('non-nullable unique_players_24h cannot be null');
        }
        $this->container['unique_players_24h'] = $unique_players_24h;

        return $this;
    }

    /**
     * Gets total_playtime_hours_24h
     *
     * @return float
     */
    public function getTotalPlaytimeHours24h()
    {
        return $this->container['total_playtime_hours_24h'];
    }

    /**
     * Sets total_playtime_hours_24h
     *
     * @param float $total_playtime_hours_24h Total playtime hours in last 24 hours
     *
     * @return self
     */
    public function setTotalPlaytimeHours24h($total_playtime_hours_24h)
    {
        if (is_null($total_playtime_hours_24h)) {
            throw new \InvalidArgumentException('non-nullable total_playtime_hours_24h cannot be null');
        }
        $this->container['total_playtime_hours_24h'] = $total_playtime_hours_24h;

        return $this;
    }

    /**
     * Gets discord_members_24h
     *
     * @return int
     */
    public function getDiscordMembers24h()
    {
        return $this->container['discord_members_24h'];
    }

    /**
     * Sets discord_members_24h
     *
     * @param int $discord_members_24h Discord members who played in last 24 hours
     *
     * @return self
     */
    public function setDiscordMembers24h($discord_members_24h)
    {
        if (is_null($discord_members_24h)) {
            throw new \InvalidArgumentException('non-nullable discord_members_24h cannot be null');
        }
        $this->container['discord_members_24h'] = $discord_members_24h;

        return $this;
    }

    /**
     * Gets unique_players_7d
     *
     * @return int
     */
    public function getUniquePlayers7d()
    {
        return $this->container['unique_players_7d'];
    }

    /**
     * Sets unique_players_7d
     *
     * @param int $unique_players_7d Unique players in last 7 days
     *
     * @return self
     */
    public function setUniquePlayers7d($unique_players_7d)
    {
        if (is_null($unique_players_7d)) {
            throw new \InvalidArgumentException('non-nullable unique_players_7d cannot be null');
        }
        $this->container['unique_players_7d'] = $unique_players_7d;

        return $this;
    }

    /**
     * Gets total_playtime_hours_7d
     *
     * @return float
     */
    public function getTotalPlaytimeHours7d()
    {
        return $this->container['total_playtime_hours_7d'];
    }

    /**
     * Sets total_playtime_hours_7d
     *
     * @param float $total_playtime_hours_7d Total playtime hours in last 7 days
     *
     * @return self
     */
    public function setTotalPlaytimeHours7d($total_playtime_hours_7d)
    {
        if (is_null($total_playtime_hours_7d)) {
            throw new \InvalidArgumentException('non-nullable total_playtime_hours_7d cannot be null');
        }
        $this->container['total_playtime_hours_7d'] = $total_playtime_hours_7d;

        return $this;
    }

    /**
     * Gets discord_members_7d
     *
     * @return int
     */
    public function getDiscordMembers7d()
    {
        return $this->container['discord_members_7d'];
    }

    /**
     * Sets discord_members_7d
     *
     * @param int $discord_members_7d Discord members who played in last 7 days
     *
     * @return self
     */
    public function setDiscordMembers7d($discord_members_7d)
    {
        if (is_null($discord_members_7d)) {
            throw new \InvalidArgumentException('non-nullable discord_members_7d cannot be null');
        }
        $this->container['discord_members_7d'] = $discord_members_7d;

        return $this;
    }

    /**
     * Gets unique_players_30d
     *
     * @return int
     */
    public function getUniquePlayers30d()
    {
        return $this->container['unique_players_30d'];
    }

    /**
     * Sets unique_players_30d
     *
     * @param int $unique_players_30d Unique players in last 30 days
     *
     * @return self
     */
    public function setUniquePlayers30d($unique_players_30d)
    {
        if (is_null($unique_players_30d)) {
            throw new \InvalidArgumentException('non-nullable unique_players_30d cannot be null');
        }
        $this->container['unique_players_30d'] = $unique_players_30d;

        return $this;
    }

    /**
     * Gets total_playtime_hours_30d
     *
     * @return float
     */
    public function getTotalPlaytimeHours30d()
    {
        return $this->container['total_playtime_hours_30d'];
    }

    /**
     * Sets total_playtime_hours_30d
     *
     * @param float $total_playtime_hours_30d Total playtime hours in last 30 days
     *
     * @return self
     */
    public function setTotalPlaytimeHours30d($total_playtime_hours_30d)
    {
        if (is_null($total_playtime_hours_30d)) {
            throw new \InvalidArgumentException('non-nullable total_playtime_hours_30d cannot be null');
        }
        $this->container['total_playtime_hours_30d'] = $total_playtime_hours_30d;

        return $this;
    }

    /**
     * Gets discord_members_30d
     *
     * @return int
     */
    public function getDiscordMembers30d()
    {
        return $this->container['discord_members_30d'];
    }

    /**
     * Sets discord_members_30d
     *
     * @param int $discord_members_30d Discord members who played in last 30 days
     *
     * @return self
     */
    public function setDiscordMembers30d($discord_members_30d)
    {
        if (is_null($discord_members_30d)) {
            throw new \InvalidArgumentException('non-nullable discord_members_30d cannot be null');
        }
        $this->container['discord_members_30d'] = $discord_members_30d;

        return $this;
    }

    /**
     * Gets daily_trend
     *
     * @return array<string,mixed>[]|null
     */
    public function getDailyTrend()
    {
        return $this->container['daily_trend'];
    }

    /**
     * Sets daily_trend
     *
     * @param array<string,mixed>[]|null $daily_trend Daily unique player counts for trend analysis
     *
     * @return self
     */
    public function setDailyTrend($daily_trend)
    {
        if (is_null($daily_trend)) {
            throw new \InvalidArgumentException('non-nullable daily_trend cannot be null');
        }
        $this->container['daily_trend'] = $daily_trend;

        return $this;
    }

    /**
     * Gets top_theatres
     *
     * @return \DcsServerBot\Model\TopTheatre[]|null
     */
    public function getTopTheatres()
    {
        return $this->container['top_theatres'];
    }

    /**
     * Sets top_theatres
     *
     * @param \DcsServerBot\Model\TopTheatre[]|null $top_theatres Top theatres by playtime
     *
     * @return self
     */
    public function setTopTheatres($top_theatres)
    {
        if (is_null($top_theatres)) {
            throw new \InvalidArgumentException('non-nullable top_theatres cannot be null');
        }
        $this->container['top_theatres'] = $top_theatres;

        return $this;
    }

    /**
     * Gets top_missions
     *
     * @return \DcsServerBot\Model\TopMission[]|null
     */
    public function getTopMissions()
    {
        return $this->container['top_missions'];
    }

    /**
     * Sets top_missions
     *
     * @param \DcsServerBot\Model\TopMission[]|null $top_missions Top missions by playtime
     *
     * @return self
     */
    public function setTopMissions($top_missions)
    {
        if (is_null($top_missions)) {
            throw new \InvalidArgumentException('non-nullable top_missions cannot be null');
        }
        $this->container['top_missions'] = $top_missions;

        return $this;
    }

    /**
     * Gets top_modules
     *
     * @return \DcsServerBot\Model\TopModule[]|null
     */
    public function getTopModules()
    {
        return $this->container['top_modules'];
    }

    /**
     * Sets top_modules
     *
     * @param \DcsServerBot\Model\TopModule[]|null $top_modules Top modules by playtime and usage
     *
     * @return self
     */
    public function setTopModules($top_modules)
    {
        if (is_null($top_modules)) {
            throw new \InvalidArgumentException('non-nullable top_modules cannot be null');
        }
        $this->container['top_modules'] = $top_modules;

        return $this;
    }

    /**
     * Gets total_sorties
     *
     * @return int|null
     */
    public function getTotalSorties()
    {
        return $this->container['total_sorties'];
    }

    /**
     * Sets total_sorties
     *
     * @param int|null $total_sorties total_sorties
     *
     * @return self
     */
    public function setTotalSorties($total_sorties)
    {
        if (is_null($total_sorties)) {
            array_push($this->openAPINullablesSetToNull, 'total_sorties');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_sorties', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_sorties'] = $total_sorties;

        return $this;
    }

    /**
     * Gets total_kills
     *
     * @return int|null
     */
    public function getTotalKills()
    {
        return $this->container['total_kills'];
    }

    /**
     * Sets total_kills
     *
     * @param int|null $total_kills total_kills
     *
     * @return self
     */
    public function setTotalKills($total_kills)
    {
        if (is_null($total_kills)) {
            array_push($this->openAPINullablesSetToNull, 'total_kills');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_kills', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_kills'] = $total_kills;

        return $this;
    }

    /**
     * Gets total_deaths
     *
     * @return int|null
     */
    public function getTotalDeaths()
    {
        return $this->container['total_deaths'];
    }

    /**
     * Sets total_deaths
     *
     * @param int|null $total_deaths total_deaths
     *
     * @return self
     */
    public function setTotalDeaths($total_deaths)
    {
        if (is_null($total_deaths)) {
            array_push($this->openAPINullablesSetToNull, 'total_deaths');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_deaths', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_deaths'] = $total_deaths;

        return $this;
    }

    /**
     * Gets total_pvp_kills
     *
     * @return int|null
     */
    public function getTotalPvpKills()
    {
        return $this->container['total_pvp_kills'];
    }

    /**
     * Sets total_pvp_kills
     *
     * @param int|null $total_pvp_kills total_pvp_kills
     *
     * @return self
     */
    public function setTotalPvpKills($total_pvp_kills)
    {
        if (is_null($total_pvp_kills)) {
            array_push($this->openAPINullablesSetToNull, 'total_pvp_kills');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_pvp_kills', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_pvp_kills'] = $total_pvp_kills;

        return $this;
    }

    /**
     * Gets total_pvp_deaths
     *
     * @return int|null
     */
    public function getTotalPvpDeaths()
    {
        return $this->container['total_pvp_deaths'];
    }

    /**
     * Sets total_pvp_deaths
     *
     * @param int|null $total_pvp_deaths total_pvp_deaths
     *
     * @return self
     */
    public function setTotalPvpDeaths($total_pvp_deaths)
    {
        if (is_null($total_pvp_deaths)) {
            array_push($this->openAPINullablesSetToNull, 'total_pvp_deaths');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_pvp_deaths', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_pvp_deaths'] = $total_pvp_deaths;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


