<?php
/**
 * Trueskill
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Model;

use \ArrayAccess;
use \DcsServerBot\ObjectSerializer;

/**
 * Trueskill Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Trueskill implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Trueskill';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'nick' => 'string',
        'date' => '\DateTime',
        'kills_pvp' => 'int',
        'deaths_pvp' => 'int',
        'true_skill' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'nick' => null,
        'date' => 'date-time',
        'kills_pvp' => null,
        'deaths_pvp' => null,
        'true_skill' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'nick' => false,
        'date' => false,
        'kills_pvp' => false,
        'deaths_pvp' => false,
        'true_skill' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nick' => 'nick',
        'date' => 'date',
        'kills_pvp' => 'kills_pvp',
        'deaths_pvp' => 'deaths_pvp',
        'true_skill' => 'TrueSkill'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nick' => 'setNick',
        'date' => 'setDate',
        'kills_pvp' => 'setKillsPvp',
        'deaths_pvp' => 'setDeathsPvp',
        'true_skill' => 'setTrueSkill'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nick' => 'getNick',
        'date' => 'getDate',
        'kills_pvp' => 'getKillsPvp',
        'deaths_pvp' => 'getDeathsPvp',
        'true_skill' => 'getTrueSkill'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('nick', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('kills_pvp', $data ?? [], null);
        $this->setIfExists('deaths_pvp', $data ?? [], null);
        $this->setIfExists('true_skill', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['nick'] === null) {
            $invalidProperties[] = "'nick' can't be null";
        }
        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ($this->container['kills_pvp'] === null) {
            $invalidProperties[] = "'kills_pvp' can't be null";
        }
        if ($this->container['deaths_pvp'] === null) {
            $invalidProperties[] = "'deaths_pvp' can't be null";
        }
        if ($this->container['true_skill'] === null) {
            $invalidProperties[] = "'true_skill' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nick
     *
     * @return string
     */
    public function getNick()
    {
        return $this->container['nick'];
    }

    /**
     * Sets nick
     *
     * @param string $nick Player's nickname
     *
     * @return self
     */
    public function setNick($nick)
    {
        if (is_null($nick)) {
            throw new \InvalidArgumentException('non-nullable nick cannot be null');
        }
        $this->container['nick'] = $nick;

        return $this;
    }

    /**
     * Gets date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime $date Last seen date of that player in ISO-format
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets kills_pvp
     *
     * @return int
     */
    public function getKillsPvp()
    {
        return $this->container['kills_pvp'];
    }

    /**
     * Sets kills_pvp
     *
     * @param int $kills_pvp Number of PvP kills
     *
     * @return self
     */
    public function setKillsPvp($kills_pvp)
    {
        if (is_null($kills_pvp)) {
            throw new \InvalidArgumentException('non-nullable kills_pvp cannot be null');
        }
        $this->container['kills_pvp'] = $kills_pvp;

        return $this;
    }

    /**
     * Gets deaths_pvp
     *
     * @return int
     */
    public function getDeathsPvp()
    {
        return $this->container['deaths_pvp'];
    }

    /**
     * Sets deaths_pvp
     *
     * @param int $deaths_pvp Number of deaths by other players
     *
     * @return self
     */
    public function setDeathsPvp($deaths_pvp)
    {
        if (is_null($deaths_pvp)) {
            throw new \InvalidArgumentException('non-nullable deaths_pvp cannot be null');
        }
        $this->container['deaths_pvp'] = $deaths_pvp;

        return $this;
    }

    /**
     * Gets true_skill
     *
     * @return float
     */
    public function getTrueSkill()
    {
        return $this->container['true_skill'];
    }

    /**
     * Sets true_skill
     *
     * @param float $true_skill TrueSkill:tm: Rating of that player
     *
     * @return self
     */
    public function setTrueSkill($true_skill)
    {
        if (is_null($true_skill)) {
            throw new \InvalidArgumentException('non-nullable true_skill cannot be null');
        }
        $this->container['true_skill'] = $true_skill;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


