<?php
/**
 * WeaponPK
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Model;

use \ArrayAccess;
use \DcsServerBot\ObjectSerializer;

/**
 * WeaponPK Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WeaponPK implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WeaponPK';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'weapon' => 'string',
        'shots' => 'int',
        'hits' => 'int',
        'pk' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'weapon' => null,
        'shots' => null,
        'hits' => null,
        'pk' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'weapon' => false,
        'shots' => false,
        'hits' => false,
        'pk' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'weapon' => 'weapon',
        'shots' => 'shots',
        'hits' => 'hits',
        'pk' => 'pk'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'weapon' => 'setWeapon',
        'shots' => 'setShots',
        'hits' => 'setHits',
        'pk' => 'setPk'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'weapon' => 'getWeapon',
        'shots' => 'getShots',
        'hits' => 'getHits',
        'pk' => 'getPk'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('weapon', $data ?? [], null);
        $this->setIfExists('shots', $data ?? [], null);
        $this->setIfExists('hits', $data ?? [], null);
        $this->setIfExists('pk', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['weapon'] === null) {
            $invalidProperties[] = "'weapon' can't be null";
        }
        if ($this->container['shots'] === null) {
            $invalidProperties[] = "'shots' can't be null";
        }
        if ($this->container['hits'] === null) {
            $invalidProperties[] = "'hits' can't be null";
        }
        if ($this->container['pk'] === null) {
            $invalidProperties[] = "'pk' can't be null";
        }
        if (!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", $this->container['pk'])) {
            $invalidProperties[] = "invalid value for 'pk', must be conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets weapon
     *
     * @return string
     */
    public function getWeapon()
    {
        return $this->container['weapon'];
    }

    /**
     * Sets weapon
     *
     * @param string $weapon Weapon type
     *
     * @return self
     */
    public function setWeapon($weapon)
    {
        if (is_null($weapon)) {
            throw new \InvalidArgumentException('non-nullable weapon cannot be null');
        }
        $this->container['weapon'] = $weapon;

        return $this;
    }

    /**
     * Gets shots
     *
     * @return int
     */
    public function getShots()
    {
        return $this->container['shots'];
    }

    /**
     * Sets shots
     *
     * @param int $shots Number of shots fired
     *
     * @return self
     */
    public function setShots($shots)
    {
        if (is_null($shots)) {
            throw new \InvalidArgumentException('non-nullable shots cannot be null');
        }
        $this->container['shots'] = $shots;

        return $this;
    }

    /**
     * Gets hits
     *
     * @return int
     */
    public function getHits()
    {
        return $this->container['hits'];
    }

    /**
     * Sets hits
     *
     * @param int $hits Number of hits
     *
     * @return self
     */
    public function setHits($hits)
    {
        if (is_null($hits)) {
            throw new \InvalidArgumentException('non-nullable hits cannot be null');
        }
        $this->container['hits'] = $hits;

        return $this;
    }

    /**
     * Gets pk
     *
     * @return string
     */
    public function getPk()
    {
        return $this->container['pk'];
    }

    /**
     * Sets pk
     *
     * @param string $pk Probability of killing
     *
     * @return self
     */
    public function setPk($pk)
    {
        if (is_null($pk)) {
            throw new \InvalidArgumentException('non-nullable pk cannot be null');
        }

        if ((!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", ObjectSerializer::toString($pk)))) {
            throw new \InvalidArgumentException("invalid value for \$pk when calling WeaponPK., must conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.");
        }

        $this->container['pk'] = $pk;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


