<?php
/**
 * WeatherInfo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DcsServerBot\Model;

use \ArrayAccess;
use \DcsServerBot\ObjectSerializer;

/**
 * WeatherInfo Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WeatherInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WeatherInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'temperature' => 'float',
        'wind_speed' => 'float',
        'wind_direction' => 'int',
        'pressure' => 'float',
        'visibility' => 'int',
        'clouds_base' => 'int',
        'clouds_density' => 'int',
        'precipitation' => 'int',
        'fog_enabled' => 'bool',
        'fog_visibility' => 'int',
        'dust_enabled' => 'bool',
        'dust_visibility' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'temperature' => null,
        'wind_speed' => null,
        'wind_direction' => null,
        'pressure' => null,
        'visibility' => null,
        'clouds_base' => null,
        'clouds_density' => null,
        'precipitation' => null,
        'fog_enabled' => null,
        'fog_visibility' => null,
        'dust_enabled' => null,
        'dust_visibility' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'temperature' => true,
        'wind_speed' => true,
        'wind_direction' => true,
        'pressure' => true,
        'visibility' => true,
        'clouds_base' => true,
        'clouds_density' => true,
        'precipitation' => true,
        'fog_enabled' => true,
        'fog_visibility' => true,
        'dust_enabled' => true,
        'dust_visibility' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'temperature' => 'temperature',
        'wind_speed' => 'wind_speed',
        'wind_direction' => 'wind_direction',
        'pressure' => 'pressure',
        'visibility' => 'visibility',
        'clouds_base' => 'clouds_base',
        'clouds_density' => 'clouds_density',
        'precipitation' => 'precipitation',
        'fog_enabled' => 'fog_enabled',
        'fog_visibility' => 'fog_visibility',
        'dust_enabled' => 'dust_enabled',
        'dust_visibility' => 'dust_visibility'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'temperature' => 'setTemperature',
        'wind_speed' => 'setWindSpeed',
        'wind_direction' => 'setWindDirection',
        'pressure' => 'setPressure',
        'visibility' => 'setVisibility',
        'clouds_base' => 'setCloudsBase',
        'clouds_density' => 'setCloudsDensity',
        'precipitation' => 'setPrecipitation',
        'fog_enabled' => 'setFogEnabled',
        'fog_visibility' => 'setFogVisibility',
        'dust_enabled' => 'setDustEnabled',
        'dust_visibility' => 'setDustVisibility'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'temperature' => 'getTemperature',
        'wind_speed' => 'getWindSpeed',
        'wind_direction' => 'getWindDirection',
        'pressure' => 'getPressure',
        'visibility' => 'getVisibility',
        'clouds_base' => 'getCloudsBase',
        'clouds_density' => 'getCloudsDensity',
        'precipitation' => 'getPrecipitation',
        'fog_enabled' => 'getFogEnabled',
        'fog_visibility' => 'getFogVisibility',
        'dust_enabled' => 'getDustEnabled',
        'dust_visibility' => 'getDustVisibility'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('temperature', $data ?? [], null);
        $this->setIfExists('wind_speed', $data ?? [], null);
        $this->setIfExists('wind_direction', $data ?? [], null);
        $this->setIfExists('pressure', $data ?? [], null);
        $this->setIfExists('visibility', $data ?? [], null);
        $this->setIfExists('clouds_base', $data ?? [], null);
        $this->setIfExists('clouds_density', $data ?? [], null);
        $this->setIfExists('precipitation', $data ?? [], null);
        $this->setIfExists('fog_enabled', $data ?? [], null);
        $this->setIfExists('fog_visibility', $data ?? [], null);
        $this->setIfExists('dust_enabled', $data ?? [], null);
        $this->setIfExists('dust_visibility', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets temperature
     *
     * @return float|null
     */
    public function getTemperature()
    {
        return $this->container['temperature'];
    }

    /**
     * Sets temperature
     *
     * @param float|null $temperature temperature
     *
     * @return self
     */
    public function setTemperature($temperature)
    {
        if (is_null($temperature)) {
            array_push($this->openAPINullablesSetToNull, 'temperature');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('temperature', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['temperature'] = $temperature;

        return $this;
    }

    /**
     * Gets wind_speed
     *
     * @return float|null
     */
    public function getWindSpeed()
    {
        return $this->container['wind_speed'];
    }

    /**
     * Sets wind_speed
     *
     * @param float|null $wind_speed wind_speed
     *
     * @return self
     */
    public function setWindSpeed($wind_speed)
    {
        if (is_null($wind_speed)) {
            array_push($this->openAPINullablesSetToNull, 'wind_speed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wind_speed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['wind_speed'] = $wind_speed;

        return $this;
    }

    /**
     * Gets wind_direction
     *
     * @return int|null
     */
    public function getWindDirection()
    {
        return $this->container['wind_direction'];
    }

    /**
     * Sets wind_direction
     *
     * @param int|null $wind_direction wind_direction
     *
     * @return self
     */
    public function setWindDirection($wind_direction)
    {
        if (is_null($wind_direction)) {
            array_push($this->openAPINullablesSetToNull, 'wind_direction');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wind_direction', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['wind_direction'] = $wind_direction;

        return $this;
    }

    /**
     * Gets pressure
     *
     * @return float|null
     */
    public function getPressure()
    {
        return $this->container['pressure'];
    }

    /**
     * Sets pressure
     *
     * @param float|null $pressure pressure
     *
     * @return self
     */
    public function setPressure($pressure)
    {
        if (is_null($pressure)) {
            array_push($this->openAPINullablesSetToNull, 'pressure');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pressure', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pressure'] = $pressure;

        return $this;
    }

    /**
     * Gets visibility
     *
     * @return int|null
     */
    public function getVisibility()
    {
        return $this->container['visibility'];
    }

    /**
     * Sets visibility
     *
     * @param int|null $visibility visibility
     *
     * @return self
     */
    public function setVisibility($visibility)
    {
        if (is_null($visibility)) {
            array_push($this->openAPINullablesSetToNull, 'visibility');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('visibility', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['visibility'] = $visibility;

        return $this;
    }

    /**
     * Gets clouds_base
     *
     * @return int|null
     */
    public function getCloudsBase()
    {
        return $this->container['clouds_base'];
    }

    /**
     * Sets clouds_base
     *
     * @param int|null $clouds_base clouds_base
     *
     * @return self
     */
    public function setCloudsBase($clouds_base)
    {
        if (is_null($clouds_base)) {
            array_push($this->openAPINullablesSetToNull, 'clouds_base');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('clouds_base', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['clouds_base'] = $clouds_base;

        return $this;
    }

    /**
     * Gets clouds_density
     *
     * @return int|null
     */
    public function getCloudsDensity()
    {
        return $this->container['clouds_density'];
    }

    /**
     * Sets clouds_density
     *
     * @param int|null $clouds_density clouds_density
     *
     * @return self
     */
    public function setCloudsDensity($clouds_density)
    {
        if (is_null($clouds_density)) {
            array_push($this->openAPINullablesSetToNull, 'clouds_density');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('clouds_density', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['clouds_density'] = $clouds_density;

        return $this;
    }

    /**
     * Gets precipitation
     *
     * @return int|null
     */
    public function getPrecipitation()
    {
        return $this->container['precipitation'];
    }

    /**
     * Sets precipitation
     *
     * @param int|null $precipitation precipitation
     *
     * @return self
     */
    public function setPrecipitation($precipitation)
    {
        if (is_null($precipitation)) {
            array_push($this->openAPINullablesSetToNull, 'precipitation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('precipitation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['precipitation'] = $precipitation;

        return $this;
    }

    /**
     * Gets fog_enabled
     *
     * @return bool|null
     */
    public function getFogEnabled()
    {
        return $this->container['fog_enabled'];
    }

    /**
     * Sets fog_enabled
     *
     * @param bool|null $fog_enabled fog_enabled
     *
     * @return self
     */
    public function setFogEnabled($fog_enabled)
    {
        if (is_null($fog_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'fog_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fog_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fog_enabled'] = $fog_enabled;

        return $this;
    }

    /**
     * Gets fog_visibility
     *
     * @return int|null
     */
    public function getFogVisibility()
    {
        return $this->container['fog_visibility'];
    }

    /**
     * Sets fog_visibility
     *
     * @param int|null $fog_visibility fog_visibility
     *
     * @return self
     */
    public function setFogVisibility($fog_visibility)
    {
        if (is_null($fog_visibility)) {
            array_push($this->openAPINullablesSetToNull, 'fog_visibility');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fog_visibility', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fog_visibility'] = $fog_visibility;

        return $this;
    }

    /**
     * Gets dust_enabled
     *
     * @return bool|null
     */
    public function getDustEnabled()
    {
        return $this->container['dust_enabled'];
    }

    /**
     * Sets dust_enabled
     *
     * @param bool|null $dust_enabled dust_enabled
     *
     * @return self
     */
    public function setDustEnabled($dust_enabled)
    {
        if (is_null($dust_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'dust_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dust_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dust_enabled'] = $dust_enabled;

        return $this;
    }

    /**
     * Gets dust_visibility
     *
     * @return int|null
     */
    public function getDustVisibility()
    {
        return $this->container['dust_visibility'];
    }

    /**
     * Sets dust_visibility
     *
     * @param int|null $dust_visibility dust_visibility
     *
     * @return self
     */
    public function setDustVisibility($dust_visibility)
    {
        if (is_null($dust_visibility)) {
            array_push($this->openAPINullablesSetToNull, 'dust_visibility');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dust_visibility', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dust_visibility'] = $dust_visibility;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


