<?php
/**
 * InfoApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DcsServerBot\Test\Api;

use \DcsServerBot\Configuration;
use \DcsServerBot\ApiException;
use \DcsServerBot\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InfoApiTest Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InfoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for currentServerServerapiCurrentServerGet
     *
     * Current Server.
     *
     */
    public function testCurrentServerServerapiCurrentServerGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getuserServerapiGetuserPost
     *
     * User list.
     *
     */
    public function testGetuserServerapiGetuserPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkmeServerapiLinkmePost
     *
     * Link Discord to DCS.
     *
     */
    public function testLinkmeServerapiLinkmePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerSquadronsServerapiPlayerSquadronsPost
     *
     * Player Squadrons.
     *
     */
    public function testPlayerSquadronsServerapiPlayerSquadronsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for serversServerapiServersGet
     *
     * Server list.
     *
     */
    public function testServersServerapiServersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for serverstatsServerapiServerstatsGet
     *
     * Server Statistics.
     *
     */
    public function testServerstatsServerapiServerstatsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for squadronMembersServerapiSquadronMembersPost
     *
     * Squadron Members.
     *
     */
    public function testSquadronMembersServerapiSquadronMembersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for squadronsServerapiSquadronsGet
     *
     * Squadron list.
     *
     */
    public function testSquadronsServerapiSquadronsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
