<?php
/**
 * StatisticsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DCSServerBot REST API
 *
 * REST functions to be used for DCSServerBot.
 *
 * The version of the OpenAPI document: 3.0.4.18
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DcsServerBot\Test\Api;

use \DcsServerBot\Configuration;
use \DcsServerBot\ApiException;
use \DcsServerBot\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StatisticsApiTest Class Doc Comment
 *
 * @category Class
 * @package  DcsServerBot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatisticsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for highscoreServerapiHighscoreGet
     *
     * Highscore.
     *
     */
    public function testHighscoreServerapiHighscoreGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for leaderboardServerapiLeaderboardGet
     *
     * Leaderboard.
     *
     */
    public function testLeaderboardServerapiLeaderboardGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerInfoServerapiPlayerInfoPost
     *
     * Player Information.
     *
     */
    public function testPlayerInfoServerapiPlayerInfoPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for statsServerapiModulestatsPost
     *
     * Module Statistics.
     *
     */
    public function testStatsServerapiModulestatsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for statsServerapiStatsPost
     *
     * Player Statistics.
     *
     */
    public function testStatsServerapiStatsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for topkdrServerapiTopkdrGet
     *
     * Top KDR.
     *
     */
    public function testTopkdrServerapiTopkdrGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for topkillsServerapiTopkillsGet
     *
     * Top Kills.
     *
     */
    public function testTopkillsServerapiTopkillsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for trapsServerapiTrapsPost
     *
     * Carrier Traps.
     *
     */
    public function testTrapsServerapiTrapsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for trueskillServerapiTrueskillGet
     *
     * TrueSkill:tm:.
     *
     */
    public function testTrueskillServerapiTrueskillGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for weaponpkServerapiWeaponpkPost
     *
     * Weapon PK.
     *
     */
    public function testWeaponpkServerapiWeaponpkPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
